FROM public.ecr.aws/lambda/python:3.11

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./app ./app

COPY ./app/algorithm ./app/algorithm

CMD ["app.app.handler"]

